@startuml

() "UI Campus Manager" as CM
() "UI Fleet Manager" as FM
() "UI Admin" as SM
() "UI User" as U

component RDG [
  <<component>>
  **RobDroneGo**
]

CM -d- RDG
FM -d- RDG
SM -d- RDG
U  -d- RDG

@enduml
