@startuml

skinparam linetype ortho

node Server1{
   component "<<Visualização>>" as V {
    }
}

node Server2{
  component "<<MasterDataLogistic>>" as MDL{
  }

  component "<<MasterDataBuilding>>" as MDB{
  }
}

node Server3{
  component "<<Planeamento>>" as P {
  }
}

node Server4{
  database MongoDB
}



Server1 -d- Server2: http/s
Server2 -u- Server3: http/s
Server2 -u- Server4
@enduml
