@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "User" as CM

CM -> System: Starts the process to edit personal data
activate System
System --> CM: Informs operation success
deactivate System

@enduml
