@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Fleet Manager" as CM

CM -> System: Adds a new robot to the fleet
activate System
CM <-- System: Informs operation success
deactivate System

@enduml
