@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Fleet Manager" as CM

CM -> System: Starts the process to add a new type of robot
System --> CM: Request data (type, brand, model, tasks)
CM -> System: Types the data
CM <-- System: Informs operation success


@enduml
