@startuml

autonumber


participant ":Template" as Template
participant Component as Component
participant ":Service" as Service
participant ":Floor" as Model
participant ":FloorEdit" as Model2
participant ":HTTP Driver" as HTTP

?o->Template: /floors
activate Template

Template -> Component: /floors/editFloor
activate Component

Component -> Model2: Parse Data to FloorEdit

Component -> Service: editFloor(floorData)
activate Service

Service -> HTTP: http put
activate HTTP
HTTP -> : PUT
HTTP --> Service: JSON
deactivate HTTP

Service -> Model: Parse JSON to Floor

Service --> Component: floor
deactivate Service

Component --> Template: operation success
deactivate Component

<--Template: operation success
deactivate Template


@enduml
