@startuml ProcessView
'https://plantuml.com/sequence-diagram

autonumber
actor "Campus Manager" as CM


activate CM
CM -> System: Create elevator 
activate System
CM <-- System: Inform Success
deactivate System

@enduml