@startuml

autonumber

participant Visualization
participant "MasterDataBuilding" as GI

?o-> Visualization: Starts the process to load a floor map
activate Visualization

Visualization -> GI: PATCH /loadFloorMap
activate GI
GI --> Visualization: buildings(JSON)
deactivate GI

<-- Visualization: Shows confirmation message
deactivate Visualization


@enduml
