@startuml

autonumber

participant Visualization
participant "MasterDataLogistics" as GI

?o-> Visualization: Consult all robots in fleet
activate Visualization


Visualization -> GI: GET robots
activate GI
GI --> Visualization: List of robots
deactivate GI

<-- Visualization: List of robots
deactivate Visualization


@enduml
