@startuml domain
skinparam linetype ortho


'========================================================
rectangle #EDB182{
class Passageway  << Root >> << Entity >>
class PassagewayId  << (v,orange) ValueObject >> << unique >>
}
'========================================================
rectangle #D499B9{
class Floor  << Root >> << Entity >>
class FloorId  << (v,orange) ValueObject >> << unique >>
class FloorDescription  << (v,#A4C2E5) ValueObject >>
class FloorMap  << Entity >>
class FloorNumber << (v,#A4C2E5) ValueObject >>
}

'========================================================

Passageway "1"-d->"1" PassagewayId

Floor "1"-d->"1" FloorMap
Floor "*"-u>"1" FloorNumber
Floor "*"->"1" FloorDescription
Floor "1" -> "1" FloorId

FloorMap "2"--->"0..*" Passageway

@enduml
