@startuml

autonumber

participant Visualization
participant "MasterDataBuilding" as GI

?o-> Visualization: Starts the process to create a buildings 
activate Visualization

Visualization -> GI: POST createBuilding
activate GI
GI --> Visualization: building(JSON)
deactivate GI

<-- Visualization: Shows confirmation message
deactivate Visualization


@enduml
