@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Campus Manager" as CM

CM -> System: Starts the process to create a building floor
System --> CM: Request data
CM -> System: Types the data
CM <-- System: Informs operation success


@enduml
