@startuml

autonumber

participant Visualization
participant "MasterDataLogistics" as GI

?o-> Visualization: inhibit a robot
activate Visualization


Visualization -> GI: PATCH robot
activate GI
GI --> Visualization: robot inhibited
deactivate GI

<-- Visualization: shows operation confirmation
deactivate Visualization


@enduml
