@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Campus Manager" as CM


activate System
CM -> System: List floors with passageways to other buildings
CM <-- System: List of floors
deactivate System

@enduml