@startuml

autonumber


participant ":Template" as Template
participant Component as Component
participant ":Service" as Service
participant ":Building" as Model
participant ":HTTP Driver" as HTTP

?o->Template: /buildings
activate Template

Template -> Component: /buildings/listAllBuildings
activate Component

Component -> Service: editBuilding(buildingDto)
activate Service

Service -> HTTP: http GET
activate HTTP
HTTP -> : GET
HTTP --> Service: JSON
deactivate HTTP

Service -> Model: Parse JSON to Building



Service --> Component:buildings 
deactivate Service

Component --> Template:buildings
deactivate Component

<--Template: buildings
deactivate Template


@enduml
