@startuml

autonumber

participant Visualization
participant "Auth" as GI

?o-> Visualization:
activate Visualization


Visualization -> GI: PUT updateUser
activate GI

GI -> GI: updateUser(user)

GI --> Visualization: user
deactivate GI


<-- Visualization:
deactivate Visualization

@enduml
