@startuml

() "UI Campus Manager" as CM
() "UI Fleet Manager" as FM
() "UI Admin" as SM
() "UI User" as U #FF6347

component RDG #FF6347  [
  <<component>>
  **RobDroneGo**

]

CM -d- RDG
FM -d- RDG
SM -d- RDG
U  -d- RDG

@enduml
