@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "User" as CM

CM -> System: Starts the process to create a task
System --> CM: Request data
CM -> System: Types the data
CM <-- System: Informs operation success


@enduml
