@startuml ProcessView

autonumber

participant Visualization
participant "MasterDataBuilding" as GI

?o-> Visualization: Edit elevator
activate Visualization

Visualization -> GI: PUT editElevator
activate GI
GI --> Visualization: elevator
deactivate GI

<-- Visualization: Inform Success
deactivate Visualization


@enduml