@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant Visualization
participant MasterDataBuilding

?o-> Visualization : editPassageway
activate Visualization

Visualization -> MasterDataBuilding : editPassageway
activate MasterDataBuilding

MasterDataBuilding --> Visualization
deactivate MasterDataBuilding

<--Visualization
deactivate Visualization

@enduml